### ISSUE TITLE
Доработка для проверки умений

### ISSUE THREAD

**Issue by arusak** [cntower/ng2play#1]
1. Подключить к сборщику PostCSS с плагинами для ЦСС-префиксов и минификации.

2. Использовать sass-подобный синтаксис в ЦСС-файлах.

```css
.slave .title {
    font-size: 36px;
    letter-spacing: 1.15pt;
    font-weight: normal;
    text-align: center;
    margin-top: 60px;
}
.slave .container {
    height: 60%;    
    margin: 0 158px;
}
.slave md-input-container {
    width: 100%;
    margin-top: 50px;
}
```

заменить на 

```scss
.slave {
  .title {
    font-size: $large-font;
    letter-spacing: 1.15pt;
    font-weight: normal;
    text-align: center;
    margin-top: 60px;
  }
  .container {
    height: 60%;    
    margin: 0 158px;
  }
  md-input-container {
    width: 100%;
    margin-top: 50px;
  }
}
```

и т. д. Подключать sass к проекту не надо. PostCSS это умеет.

3. Доделать по существу задачи — чтобы приложение работало.

4. Покрыть код компонентов тестами. Я намеренно не пишу, что именно проверять, это на ваше усмотрение как разработчика. Тестов должно быть достаточно для контроля регрессионных изменений.

5. (если останется время) Сделать вёрстку адаптивной — чтобы работала на широких (больше 1600), средних (больше 800) и узких экранах.
